apiVersion: 1

datasources:
  - name: dqp
    type: postgres
    url: db-dqp:5432
    user: grafana_user
    secureJsonData:
      password: 'grafana_password'
    jsonData:
      database: dqp_db
      sslmode: 'disable'
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1303
      timescaledb: false
