{
 "title": "DQ Сравнение выручки",
 "time": { "from": "2011-04-04T16:43:08.476Z", "to": "2016-07-25T06:07:44.624Z" },
 "templating": {
  "list": [
   {
    "name": "aggregation",
    "label": "Агрегация",
    "query": "Неделя : weekly, Месяц : monthly"
   },
   {
    "name": "agg_uuid",
    "query": "select \n    case\n        when ${aggregation:singlequote} = 'monthly' then '55742de1-95c6-45b7-80a3-cf3502c56a3d'\n        when ${aggregation:singlequote} = 'weekly' then 'facb8e28-3006-4414-9737-a4e4bd2db62b'\n        else ''\n    end"
   }
  ]
 },
 "panels": [
  {
   "title": "Неделя",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with cte_postgres as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = 'facb8e28-3006-4414-9737-a4e4bd2db62b'\r\n    and task = 'transfer_postgres_weekly'\r\n  group by 1\r\n  order by 1 desc\r\n), cte_clickhouse as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = 'facb8e28-3006-4414-9737-a4e4bd2db62b'\r\n    and task = 'transfer_clickhouse_weekly'\r\n  group by 1\r\n  order by 1 desc\r\n)\r\nselect ROUND(((cc.revenue / cp.revenue) :: DECIMAL(10,2) - 1) * 100, 2) as \"% прибыль\"\r\nfrom cte_postgres cp\r\nleft join cte_clickhouse cc\r\n  on cp.valid_from_dttm = cc.valid_from_dttm\r\norder by 1 desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Месяц",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with cte_postgres as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '55742de1-95c6-45b7-80a3-cf3502c56a3d'\r\n    and task = 'transfer_postgres_monthly'\r\n  group by 1\r\n  order by 1 desc\r\n), cte_clickhouse as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '55742de1-95c6-45b7-80a3-cf3502c56a3d'\r\n    and task = 'transfer_clickhouse_monthly'\r\n  group by 1\r\n  order by 1 desc\r\n)\r\nselect ROUND(((cc.revenue / cp.revenue) :: DECIMAL(10,2) - 1) * 100, 2) as \"% прибыль\"\r\nfrom cte_postgres cp\r\nleft join cte_clickhouse cc\r\n  on cp.valid_from_dttm = cc.valid_from_dttm\r\norder by 1 desc\r\nlimit 1;"
    }
   ]
  },
  {
   "title": "Последнее обновление DQ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "rawSql": "select MAX(_updated_dttm)\r\nfrom data_quality_checks.customers_analytics__sales_data;"
    }
   ]
  },
  {
   "title": "График выручки",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Table query\r\nwith cte_postgres as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_postgres_${aggregation}'\r\n  group by 1\r\n), cte_clickhouse as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_clickhouse_${aggregation}'\r\n  group by 1\r\n)\r\nselect\r\n  cp.valid_from_dttm :: date as \"Дата сверки\"\r\n  , cp.cost as \"Postgres выручка\"\r\n  , cc.cost as \"Clickhouse выручка\"\r\n  , ROUND(((cc.cost / cp.cost) :: DECIMAL(10,2) - 1) * 100, 2) as \"% отклонения выручки\"\r\nfrom cte_postgres cp\r\nleft join cte_clickhouse cc\r\n  on cp.valid_from_dttm = cc.valid_from_dttm\r\norder by 1 desc;"
    }
   ]
  },
  {
   "title": "График прибыли",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "-- Table query\r\nwith cte_postgres as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_postgres_${aggregation}'\r\n  group by 1\r\n), cte_clickhouse as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_clickhouse_${aggregation}'\r\n  group by 1\r\n)\r\nselect\r\n  cp.valid_from_dttm :: date as \"Дата сверки\"\r\n  , cp.revenue as \"Postgres прибыль\"\r\n  , cc.revenue as \"Clickhouse прибыль\"\r\n  , ROUND(((cc.revenue / cp.revenue) :: DECIMAL(10,2) - 1) * 100, 2) as \"% отклонения прибыли\"\r\nfrom cte_postgres cp\r\nleft join cte_clickhouse cc\r\n  on cp.valid_from_dttm = cc.valid_from_dttm\r\norder by 1 desc;"
    }
   ]
  },
  {
   "title": "Сравнение на дату",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "-- Table query\r\nwith cte_postgres as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_postgres_${aggregation}'\r\n  group by 1\r\n), cte_clickhouse as (\r\n  select\r\n    valid_from_dttm\r\n    , SUM(cost) as cost\r\n    , SUM(revenue) as revenue\r\n  from data_quality_checks.customers_analytics__sales_data\r\n  where key = '${agg_uuid}'\r\n    and task = 'transfer_clickhouse_${aggregation}'\r\n  group by 1\r\n)\r\nselect\r\n  cp.valid_from_dttm as \"Дата сверки\"\r\n  , cp.cost as \"Postgres выручка\"\r\n  , cc.cost as \"Clickhouse выручка\"\r\n  , ABS(cp.cost - cc.cost) as \"abs выручка\"\r\n  , ROUND(((cc.cost / cp.cost) :: DECIMAL(10,2) - 1) * 100, 2) as \"% выручка\"\r\n  , cp.revenue as \"Postgres прибыль\"\r\n  , cc.revenue as \"Clickhouse прибыль\"\r\n  , ABS(cp.revenue - cc.revenue) as \"abs прибыль\"\r\n  , ROUND(((cc.revenue / cp.revenue) :: DECIMAL(10,2) - 1) * 100, 2) as \"% прибыль\"\r\nfrom cte_postgres cp\r\nleft join cte_clickhouse cc\r\n  on cp.valid_from_dttm = cc.valid_from_dttm\r\norder by 1 desc;"
    }
   ]
  }
 ]
}